[supervisord]
nodaemon=false
logfile=/tmp/rakazo/supervisord.log
logfile_maxbytes=5MB
logfile_backups=1
pidfile=/tmp/rakazo/supervisord.pid
childlogdir=/tmp/rakazo
user=rakazo

[inet_http_server]
port=127.0.0.1:9011

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files=/etc/rakazo/services.d/*.conf
